function [val]=evaluate_objective_noreg(Tr,R,target,configs)
val=1/2*(configs.lambda_1*trace(R'*Tr.L_user*R)+...
    configs.lambda_2*trace(R*Tr.L_poi*R')+...
    configs.lambda_3*sum(sum((R-target).^2)));
end